### ISSUE TITLE
Query.Returns does not use PostProcessor when mapping database column to a different Object property. Query.ReturnsSingle DOES.

### ISSUE THREAD

**Issue by tv14** [jonwagner/Insight.Database#343]
Hey there, 

I've currently encountered an issue where Insight would not use postprocessor to map a database column to a Object property of a different name when using Query,Returns. However, when using Query.ReturnSingle, the postprocessor properly maps the Object.

Full explanation below:

I have 3 classes:
A Doctor class which takes a single Patient,
A Patient class which takes a single Body object
The Body class stores the confidential Height and Weight of the Patient.

```
public class Doctor
	{
		public string Id { get; set; }
		public string Name { get; set; }
		public Patient Patient { get; set; }
	}
```

```	
public class Patient
	{
		public string Id { get; set; }
		public string Name { get; set; }
		public Body Body { get; set; }
	}
```

```
public class Body
	{
		public double Height { get; set; }
		public double Weight { get; set; }

		public Body()
		{
		}
		public Body (string encryptedMedicalRecords)
		{
			// decrypts medical records into height and weight
			Match match = Regex.Match(encryptedMedicalRecords, "[0-9]+");

			Height = Double.Parse(match.Value);
			Weight = Double.Parse(match.NextMatch().Value);
		}
	}
```

In the Database, the Body information is encrypted and stored in the body as an encrypted record
```
CREATE TABLE DOCTOR (ID nvchar(50), NAME nvchar(50));
CREATE TABLE DOCTOR_PATIENT_RELATION (DOCTOR_ID nvchar(50),PATIENT_ID nvchar(50));
CREATE TABLE PATIENT (ID nvchar(50), NAME nvchar(50), ENCRYPTED_RECORDS nvchar(50) );

INSERT [DOCTOR] ([ID], [NAME]) VALUES (N'doctor1', N'Patrick')
INSERT [DOCTOR] ([ID], [NAME]) VALUES (N'doctor2', N'Michael')
INSERT [DOCTOR] ([ID], [NAME]) VALUES (N'doctor3', N'Phil')
INSERT [DOCTOR_PATIENT_RELATION] ([DOCTOR_ID], [PATIENT_ID]) VALUES (N'doctor1', N'patient1')
INSERT [DOCTOR_PATIENT_RELATION] ([DOCTOR_ID], [PATIENT_ID]) VALUES (N'doctor2', N'patient3')
INSERT [DOCTOR_PATIENT_RELATION] ([DOCTOR_ID], [PATIENT_ID]) VALUES (N'doctor3', N'patient4')
INSERT [PATIENT] ([ID], [NAME], [ENCRYPTED_MEDICAL_RECORDS]) VALUES (N'patient1', N'Bob', N'h60w120')
INSERT [PATIENT] ([ID], [NAME], [ENCRYPTED_MEDICAL_RECORDS]) VALUES (N'patient3', N'Cassandra', N'h54w110')
INSERT [PATIENT] ([ID], [NAME], [ENCRYPTED_MEDICAL_RECORDS]) VALUES (N'patient4  ', N'Michelle', N'h52w100')
```

I wish to obtain the list of all the Doctors and therefore use the following SQL statement:
```
SELECT * FROM DOCTOR;
SELECT DOCTOR_ID, *
FROM PATIENT INNER JOIN DOCTOR_PATIENT_RELATION
ON PATIENT_ID=PATIENT.ID
```

In order to decrypt the medical records, I use a postprocessor which reads the ENCRYPTED_RECORDS and returns a Patient with the appropriate Body Object.

```
public static class BasicPostProcessor
{
	public static PostProcessRecordReader<Patient> DecryptMedicalRecords = new PostProcessRecordReader<Patient>(
	(reader, PatientInformation) =>
	{
		if (PatientInformation != null)
		{
			string encryptedRecords = reader["ENCRYPTED_MEDICAL_RECORDS"].ToString();
			if (!string.IsNullOrEmpty(encryptedRecords))
			{
				//sample decryption
				PatientInformation.Body = new Body(encryptedRecords);
				return PatientInformation;
			}
			else
			{
				throw new NullDatabaseRecordException("Provider in database is invalid");
			}
		}
		else
		{
			throw new ArgumentNullException(nameof(PatientInformation));
		}
	});
}
```

When I use Query.Returns to obtain a list of Doctors, The Patient properties gets mapped, but the Body object remains null. However, when I use Query.ReturnSingle for a single Doctor, the Body get properly mapped.

```
public static void Main(string[] args)
{
	// We ignore the underscores
	ColumnMapping.Tables.ReplaceRegex("_", String.Empty);

	using (var connection = new SqlConnectionStringBuilder(@"Data Source=MYPC\SQL2016;Initial Catalog=MyHospital;User ID=ADMIN;password=ADMIN;").Connection())
	{
		connection.Open();
		string SELECT_ALL_DOCTORS = @"--Get the doctors
									SELECT * FROM DOCTOR;
									
									--Get the patients
									SELECT DOCTOR_ID, *
									FROM PATIENT INNER JOIN DOCTOR_PATIENT_RELATION
									ON PATIENT_ID=PATIENT.ID";
		//NOT WORKING :( !!!
		// The body is always null...
		var doctorList = connection.QuerySql(SELECT_ALL_DOCTORS,
					null,
					Query.Returns(Some<Doctor>.Records)
					.ThenChildren(BasicPostProcessor.DecryptMedicalRecords, into: (doctor, patient) =>
					{
						doctor.Patient = patient.FirstOrDefault();
					}));

		//WORKING!!!
		var singleDoctor = connection.QuerySql(SELECT_ALL_DOCTORS,
			null,
			Query.ReturnsSingle(Some<Doctor>.Records)
			.ThenChildren(BasicPostProcessor.DecryptMedicalRecords, into: (doctor, patient) =>
			{
				doctor.Patient = patient.FirstOrDefault();
			}));
	}
}
```

Is there way a for the Postprocessor to work with Query.Returns as well?

I notice that the problem is in the ThenChildren function. The first overload of ThenChildren implementation calls another ThenChildren(), and this one is not working. It does the following line:
```
return previous.ThenChildren(recordReader.GroupByAuto<T1, object>(), null, into);
```

The second one that is working (ReturnsSingle), does not call another ThenChildren. Instead, it calls AddChild like this:
```
return previous.AddChild(new SingleChildren<T1, T2>(recordReader, new SingleChildMapper<T1, T2>(into)));
```

Do you have a better idea why I have thisw issue.

And btw, I really like InsightDb and I use it for a lot of projects. It will be great if you can help with this issue.

Thank you!

Example: https://imgur.com/a/tHp3C

See link for full program code:  
https://www.dropbox.com/sh/zxv4qy9gee5qzsq/AAC9QrWXVQtu99BsokJuqoK-a?dl=0

**Comment by jonwagner** [comment]
Sounds like a bug to me. Post processing isn't that common, so it looks like we missed it. I'll find some time to fix it.

**Comment by jonwagner** [comment]
Cause: when Insight reads the child record, if parent id fields aren't in the child object, Insight creates a "guardian" reader to read the linking fields. The PostProcessingReader didn't inject its post read method in that case.

This is fixed in 6.1.1.

**Comment by tv14** [comment]
The fix is still not good. 

With your fix, I can reach the postProcessor, however the reader is null and therefore the program crashes. 

I noticed that you pass a null value to the guardian reader; according to my understand, that null value is the reader and that's why when I get to the postProcesssor, the reader is null.  

We need the reader in the postProcessor as it is used to decrypt the medical records (see: BasicPostProcessor/DecryptMedicalRecords ).

**Comment by jonwagner** [comment]
Ah, if you need access to the reader, it's going to take some more work.

An alternative for you to try:

    public class Record {
        public Body Body;

        [Column("ENCRYPTED_RECORDS")]
        private string encryptedData {
            get { return encrypt(body); }
            set { Body = this.decrypt(value); }
        }
    }

If you bind the private property to the column, Insight will use the getter/setter to access the data.

**Comment by tanbchr** [comment]
Hi John!

Me and tv14 are working together.

We gave you that example just explain the cause of the problem. However, we use the PostProcessor for more heavy processing and in other scenarios. We do really need to have access to the reader in the PpostProcessor in that scenario.

How much time do you think is it gonna take to be able to make it work?

It would be really nice if you can fix that problem for us :)

Thank you again for the nice work and the quick feedback!

**Comment by jonwagner** [comment]
It's probably less than a few hours of work to get it right, but finding the time could be an issue.

**Comment by jonwagner** [comment]
You're in luck. I think the fix in the `wags/issue343` branch fixes it.

Are you able to pull down the branch and build it?

**Comment by tanbchr** [comment]
Thank you Jon!

We will pull the branch and test it on our side. We will give you a feedback as soon as we try it.

**Comment by tv14** [comment]
Yes it works!

We're going to need to update most of our projects and we would love get this fix pushed into master ASAP. Thanks again for working through this issue with us Jon!

**Comment by tv14** [comment]
Hello Jon, 

We still need this fix in master. While the fix is good, we use Insight a lot of our big projects. Thus, updating our databases to a branch version isn't practical, as we will have to reupdate after the next commit.

We would really appreciate it if this fix was pushed into master.

**Comment by jonwagner** [comment]
I'm planning on doing a build today
________________________________

**Comment by tanbchr** [comment]
Thank you Jon!
