### ISSUE TITLE
If i have table column with varchar(4001) insight is not working

### ISSUE THREAD

**Issue by Mahi957** [jonwagner/Insight.Database#448]
below is the code from C# console app,

public void InsertRecordsandErrors<T>( List<ErrorRecord> errorRecords)
{
      try
         {
               
            //var Errors = new SqlParameter("@Errors", SqlDbType.Udt, (int)SqlMetaData.Max);
            GetConnection().Execute("[InsertPdsData]", new
                {
                    Errors = errorRecords,
                    SomeId = 1
                });
         }
         catch (Exception ex)
         {
                //log
         }

}

below is the for SQL,

CREATE TYPE [ErrorRecord] AS TABLE(
	[Id] [int] NULL,
	[TableId] [int] NULL,
	[DocTypeRowPK] [int] NULL,
	[ErrorJson] varchar(4001) NULL--varchar(4001)
)
GO

CREATE PROCEDURE [InsertPdsData]
@Errors [ErrorRecord] READONLY,
@SomeId INT

AS BEGIN
--body
END
GO

Issue : Specified length '4001' is out of range. (Parameter 'maxLength')

**Comment by jonwagner** [comment]
I'm taking a look at this. In your table type it looks like there's no length definition on errorjson?

```
[ErrorJson] varchar NULL
```

If you don't specify a length, SQL Server will make the max length 1 and will throw that error if you send anything longer. See: https://www.sqlshack.com/sql-varchar-data-type-deep-dive/

Or is that a typo when you pasted the code? Can you please clarify your table structure?

**Comment by Mahi957** [comment]
Issue will be raised for all below columns,

ErrorJson varchar(max),
Column1 varchar(4001),

In both the cases as length is more than 4000 in those cases I am getting
exception. If all varchar columns is below 4000 it is working fine.


Thanks
Mahesh Daram

**Comment by jonwagner** [comment]
Got it. I was able to reproduce this and it is fixed in v6.3.3

**Comment by Mahi957** [comment]
In 6.3.3 Insight.DatabaseCore we are having the issue still.

**Comment by jonwagner** [comment]
@Mahi957 There is a test case in this file specific to this issue. I was able to reproduce the issue you described and 6.3.3 fixes this specific case, but there may be other variations that are not fully covered. If you can modify the case so that it breaks, we can reproduce and fix the issue.

https://github.com/jonwagner/Insight.Database/blob/main/Insight.Tests/TableValuedParametersTests.cs

**Comment by Mahi957** [comment]
If we are sending list of objects as parameters whose one column is 4001 it is not working. If i send only single object whose one of column is 4001 it is working.

below is the snippet,

public void InsertErrorsWithInsight()
        {
            //string connectionString ="";
            List<ErrorRecord> errorRecords = new List<ErrorRecord>();

            //ErrorRecord columns in both table and class
            //TableId//int
            //ErrorJson//varchar(max)
            //ErrorJson2//varchar(4001)

            errorRecords.Add(new ErrorRecord(1, 1, "hfkjsahfkdhk", "jfgjdgjfgs"));
            errorRecords.Add(new ErrorRecord(2, 2, "hfkjsahfkdhk", ""));
            try
            {

                //below is working
                GetConnection().Execute("sp_name", errorRecords[1]);//here sp  have 3 diff parameters


                //not working
                GetConnection().Execute("sp_name", errorRecords[1]);//here sp updated have single parameter iwth sql user defined type for ErrorRecord

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }

**Comment by Mahi957** [comment]
Issue is fixed in 6.3.3.
